name: rf2aa
channels:
  - pytorch
  - nvidia
  - dglteam/label/cu118
  - pyg
  - https://conda.rosettacommons.org
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - pytorch=*=*cuda*
  - pytorch-cuda=11.8
  - torchdata
  - dgl
  - pyg
  - pyrosetta
  - hhsuite
  - csblast
  - biocore::blast-legacy
  - biocore::psipred
  - e3nn
  - omegaconf
  - hydra-core
  - pyrsistent
  - opt-einsum
  - sympy
  - pydantic
  - icecream
  - wandb
  - deepdiff
  - assertpy
  - openbabel
  - numpy
  - pandas
  - seaborn
  - matplotlib
  - jupyter
  - pip
  - pip:
    - git+https://github.com/NVIDIA/dllogger.git@0540a43971f4a8a16693a9de9de73c1072020769
